version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules   # evita que el bind mount tape las deps
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  node_modules:
